-- MySQL Script generated by MySQL Workbench
-- Wed Sep  5 19:03:18 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pitaya
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pitaya
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pitaya` DEFAULT CHARACTER SET utf8 ;
USE `pitaya` ;

-- -----------------------------------------------------
-- Table `pitaya`.`tipo_proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pitaya`.`tipo_proveedor` (
  `idtipo_proveedor` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(125) NOT NULL,
  PRIMARY KEY (`idtipo_proveedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pitaya`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pitaya`.`proveedores` (
  `idproveedor` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `con_nombre` VARCHAR(125) NOT NULL,
  `con_email` VARCHAR(80) NOT NULL,
  `con_telefono` VARCHAR(10) NOT NULL,
  `con_extension` VARCHAR(3) NOT NULL,
  `status` CHAR(2) NOT NULL,
  `fk_tipo` INT(11) NOT NULL,
  PRIMARY KEY (`idproveedor`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC),
  INDEX `fk_tipo_idx` (`fk_tipo` ASC),
  INDEX `nombre_INDEX` (`nombre` ASC),
  CONSTRAINT `fk_tipo`
    FOREIGN KEY (`fk_tipo`)
    REFERENCES `pitaya`.`tipo_proveedor` (`idtipo_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pitaya`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pitaya`.`productos` (
  `idproducto` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  `descripcion` MEDIUMTEXT NOT NULL,
  `tiempo_respuesta` VARCHAR(45) NOT NULL,
  `capacidad_produccion` INT(11) NOT NULL,
  `lugar_entrega` VARCHAR(10) NOT NULL,
  `fk_proveedor` INT(11) NOT NULL,
  PRIMARY KEY (`idproducto`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC),
  INDEX `fk_proveedor_idx` (`fk_proveedor` ASC),
  INDEX `nombre_INDEX` (`nombre` ASC),
  CONSTRAINT `fk_proveedor`
    FOREIGN KEY (`fk_proveedor`)
    REFERENCES `pitaya`.`proveedores` (`idproveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pitaya`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pitaya`.`usuarios` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(125) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `rol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
